### ISSUE TITLE
Support aws_rds_cluster

### ISSUE THREAD

**Issue by sundowndev** [cloudskiff/driftctl#947]
**Description**

As we plan to support appautoscaling resources (#276), it makes sense to support RDS resources next so users can control drifts on both RDS and the autoscaler.

### Todo

- [x] Resource implementation (https://github.com/cloudskiff/driftctl/pull/1010)
- [x] Documentation (https://github.com/cloudskiff/driftctl-docs/pull/108)
- [x] QA IAM policy update (https://github.com/cloudskiff/tf-aws/pull/33)

### References

- [RDS usage with autoscaling](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_target#aurora-read-replica-autoscaling)
- [aws_rds_cluster resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance)

**Comment by sjourdan** [comment]
"impermanence" on Discord reported the following issue: 

- using the `aws_rds_cluster` resource with PgSQL
- driftctl 0.14 reports an unmanaged `aws_db_instance` 

```shell
Found resources not covered by IaC:
  aws_db_instance:
    - ue2-qa-postgres-1
```

Probably very easy to replicate on our side.

**Comment by sundowndev** [comment]
@jonassteinberg1 Thanks for report! I've investigated your case and it seems those `aws_db_instance` are managed by RDS as cluster instances. it means you have a managed `aws_rds_cluster_instance` with id `ue2-qa-postgres-1` that created this resource without importing it in the state. That's a good thing to know to help us implement RDS resources the right way.

For the record, here's a snippet to reproduce the false positive : 

```hcl
resource "aws_rds_cluster_instance" "cluster_instances" {
  count              = 3
  identifier         = "aurora-cluster-demo-${count.index}"
  cluster_identifier = aws_rds_cluster.postgresql.id
  instance_class     = "db.r4.large"
  engine             = aws_rds_cluster.postgresql.engine
  engine_version     = aws_rds_cluster.postgresql.engine_version
}

resource "aws_rds_cluster" "postgresql" {
  cluster_identifier      = "aurora-cluster-demo"
  engine                  = "aurora-postgresql"
  availability_zones      = ["us-east-1a", "us-east-1d", "us-east-1b", "us-east-2a"]
  database_name           = "mydb"
  master_username         = "foo"
  master_password         = "u9816398715"
  backup_retention_period = 5
  preferred_backup_window = "07:00-09:00"
}

resource "aws_appautoscaling_target" "replicas" {
  service_namespace  = "rds"
  scalable_dimension = "rds:cluster:ReadReplicaCount"
  resource_id        = "cluster:${aws_rds_cluster.postgresql.id}"
  min_capacity       = 1
  max_capacity       = 15
}

resource "aws_appautoscaling_policy" "replicas" {
  name               = "cpu-auto-scaling"
  service_namespace  = aws_appautoscaling_target.replicas.service_namespace
  scalable_dimension = aws_appautoscaling_target.replicas.scalable_dimension
  resource_id        = aws_appautoscaling_target.replicas.resource_id
  policy_type        = "TargetTrackingScaling"

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "RDSReaderAverageCPUUtilization"
    }

    target_value       = 75
    scale_in_cooldown  = 300
    scale_out_cooldown = 300
  }
}
```

**Comment by sjourdan** [comment]
using < 0.16: 

```sh

**Comment by sjourdan** [comment]
It seems to works as expected using directly `aws_rds_cluster`! 
But something is wrong when using the `db` module: 

using < 0.16

```sh
❯  driftctl scan 
Found resources not covered by IaC:
  aws_rds_cluster:
    - test-aurora-db-postgres96
[...]
```

Using =0.16

```sh
[...]
Found resources not covered by IaC:
  aws_rds_cluster:
    - test-aurora-db-postgres96
```

To reproduce, use the `db` module: 

```hcl 
module "db" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "~> 3.0"

  name           = "test-aurora-db-postgres96"
  engine         = "aurora-postgresql"
  engine_version = "11.9"
  instance_type  = "db.r5.large"

  vpc_id  = "vpc-d6e3c7ac" # CHANGEME
  subnets = ["subnet-8cdbd3eb", "subnet-4e584c12"] # CHANGEME

  replica_count           = 1

  storage_encrypted   = true
  apply_immediately   = true

  enabled_cloudwatch_logs_exports = ["postgresql"]

  tags = {
    Environment = "dev"
    Terraform   = "true"
  }
} 
```

tfstate excerpt: 

```json
   {
      "module": "module.db",
      "mode": "managed",
      "type": "aws_rds_cluster_instance",
      "name": "this",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "index_key": 0,
          "schema_version": 0,
          "attributes": {
            "apply_immediately": true,
            "arn": "arn:aws:rds:us-east-1:141177182257:db:test-aurora-db-postgres96-1",
            "cluster_identifier": "test-aurora-db-postgres96",
            "id": "test-aurora-db-postgres96-1",
            "identifier": "test-aurora-db-postgres96-1",
[...]
```

Using debug level we can see this warning: 

```
WARN[0001] Could not read from state: unexpected end of JSON input name=this state=tfstate://terraform.tfstate type=aws_rds_cluster
```

**Comment by sundowndev** [comment]
@sjourdan Just merged a fix (#1086), could test this again ? Thanks

**Comment by sjourdan** [comment]
I confirm it's now fixed @sundowndev :clap: 

let's talk next week about deep mode issues in this case:

```
Found changed resources:
  - test-aurora-db-postgres96-1 (aws_db_instance):
      + address: <nil> => "test-aurora-db-postgres96-1.cst8vk4dkt82.us-east-1.rds.amazonaws.com" (computed)
      + allocated_storage: <nil> => 1 (computed)
      + backup_retention_period: <nil> => 7 (computed)
      + backup_window: <nil> => "02:00-03:00" (computed)
      + character_set_name: <nil> => "" (computed)
      - cluster_identifier: "test-aurora-db-postgres96" => <nil>
      + customer_owned_ip_enabled: <nil> => false
      - db_parameter_group_name: "default.aurora-postgresql11" => <nil>
      - dbi_resource_id: "db-UEMCBIN2L3QES5HMV47JYTTOXQ" => <nil>
      + deletion_protection: <nil> => false
      + domain: <nil> => ""
      + domain_iam_role_name: <nil> => ""
      + enabled_cloudwatch_logs_exports: <nil> => ["postgresql"]
      ~ endpoint: "test-aurora-db-postgres96-1.cst8vk4dkt82.us-east-1.rds.amazonaws.com" => "test-aurora-db-postgres96-1.cst8vk4dkt82.us-east-1.rds.amazonaws.com:5432" (computed)
      + hosted_zone_id: <nil> => "Z2R2ITUGPM61AM" (computed)
      + iam_database_authentication_enabled: <nil> => false
      + iops: <nil> => 0
      + license_model: <nil> => "postgresql-license" (computed)
      + maintenance_window: <nil> => "sun:05:00-sun:06:00" (computed)
      + max_allocated_storage: <nil> => 0
      + multi_az: <nil> => false (computed)
      + name: <nil> => "" (computed)
      + nchar_character_set_name: <nil> => "" (computed)
      + option_group_name: <nil> => "default:aurora-postgresql-11" (computed)
      + parameter_group_name: <nil> => "default.aurora-postgresql11" (computed)
      + performance_insights_retention_period: <nil> => 0 (computed)
      - preferred_backup_window: "02:00-03:00" => <nil>
      - preferred_maintenance_window: "sun:05:00-sun:06:00" => <nil>
      - promotion_tier: 1 => <nil>
      + replicate_source_db: <nil> => ""
      + resource_id: <nil> => "db-UEMCBIN2L3QES5HMV47JYTTOXQ" (computed)
      + status: <nil> => "available" (computed)
      + storage_type: <nil> => "aurora" (computed)
      + timezone: <nil> => "" (computed)
      + username: <nil> => "root" (computed)
      + vpc_security_group_ids: <nil> => ["sg-01fbf8900076e9988"] (computed)
      - writer: true => <nil>
  From tfstate://terraform.tfstate
    - test-aurora-db-postgres96 (module.db.aws_rds_cluster.this):
        - allow_major_version_upgrade: false => <nil>
        - apply_immediately: true => <nil> (computed)
        - final_snapshot_identifier: "final-test-aurora-db-postgres96-1ba9f53a" => <nil>
        - source_region: "" => <nil>
Found 14 resource(s)
 - 28% coverage
 - 4 resource(s) managed by terraform
     - 2/4 resource(s) out of sync with Terraform state
 - 10 resource(s) not managed by Terraform
 - 0 resource(s) found in a Terraform state but missing on the cloud provider
You have diffs on computed fields, check the documentation for potential false positive drifts: https://docs.driftctl.com/limitations
Scan duration: 22s
Provider version used to scan: 3.61.0. Use --tf-provider-version to use another version.
```

**Comment by sundowndev** [comment]
@sjourdan the false positives you encountered should be fixed now.
